#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_pkgname() works", {

  kwb.pkgbuild:::get_pkgname("kwb.test")

  expect_error({
    withr::with_dir(create_pkg_temp(), {
      kwb.pkgbuild:::get_pkgname()})
  })

  withr::with_dir(create_pkg_temp(),{
   usethis::proj_set(getwd())
   kwb.pkgbuild::use_description()
   kwb.pkgbuild:::get_pkgname()})
})

