#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("write_to_rbuildignore() works", {

  expect_error(
    kwb.pkgbuild:::write_to_rbuildignore()
    # argument "ignore_pattern" is missing, with no default
  )

})

