#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2018-12-20 11:03:49.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("create_pkg_dir() works", {

  expect_error({
    pkg_dir <- file.path(tempdir(), "pkgname/pkgname")
    kwb.pkgbuild:::create_pkg_dir(pkg_dir)

  })

  create_pkg_dir(file.path(tempdir(), "pkgname"))

})

