#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_description() works", {
  old_wd <- create_pkg_temp()
  aut <- list(name = "Michael Rustler",
              orcid = NULL,
              url = "https://mrustl.de")
  kwb.pkgbuild:::use_description(author = aut,
                                 funder = "BMBF")
  setwd(old_wd)
})

