#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_installation() works", {

  expect_error(
    kwb.pkgbuild:::use_installation()
    # argument "domain" is missing, with no default
  )

})

