#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_news_md() works", {
  old_wd <- create_pkg_temp()
  kwb.pkgbuild:::use_news_md()
  kwb.pkgbuild:::use_news_md() ## now no news should be created
  setwd(old_wd)

})

