#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_pkg() works", {
  old_wd <- create_pkg_temp()
  pkg_dir <- getwd()
  fs::file_delete(file.path(pkg_dir, "DESCRIPTION"))
  kwb.pkgbuild:::use_pkg()
  setwd(old_wd)
})

