#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_pkgname() works", {

  kwb.pkgbuild:::get_pkgname("kwb.test")

  old_wd <- create_pkg_temp()
  kwb.pkgbuild:::get_pkgname()
  setwd(old_wd)

  expect_error({
    old_wd <- setwd(dir = tempdir())
    tryCatch(kwb.pkgbuild:::get_pkgname(),
     finally = setwd(old_wd))})


})

