#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_badge_cran() works", {

  expect_error(
    kwb.pkgbuild:::use_badge_cran()
    # argument "pkgname" is missing, with no default
  )

})

