#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_badge_appveyor() works", {

  expect_error(
    kwb.pkgbuild:::use_badge_appveyor()
    # argument "repo" is missing, with no default
  )

})

