#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_installation() works", {

    kwb.pkgbuild:::use_installation(pkgname = "kwb.umberto",
                                    user = "KWB-R",
                                    domain = "github")


})

