#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("read_description() works", {

  expect_error(
    withr::with_dir(tempdir(), {kwb.pkgbuild:::read_description()})
  )

  withr::with_dir(create_pkg_temp(), {
    usethis::proj_set(getwd())
    kwb.pkgbuild::use_description()
    kwb.pkgbuild:::read_description()})
})

