#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_mit_license() works", {
  old_wd <- create_pkg_temp()
  cph <- list(name ="Kompetenzzentrum Wasser Berlin gGmbH (KWB)",
       start_year = 2018)
  kwb.pkgbuild:::use_mit_license(copyright_holder = cph)
  setwd(old_wd)
})

