#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2018-12-20 11:03:50.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("write_git_batch_and_execute() works", {

  expect_error(
    kwb.pkgbuild:::write_git_batch_and_execute()
    # argument "git_exe" is missing, with no default
  )

})

