#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_mit_license() works with defaults", {
  withr::with_dir(create_pkg_temp(), {
    usethis::proj_set(getwd())
    kwb.pkgbuild::use_description()
    kwb.pkgbuild:::use_mit_license()})
})


test_that("use_mit_license() works with defined start_year", {
  withr::with_dir(create_pkg_temp(), {
  usethis::proj_set(getwd())
  kwb.pkgbuild::use_description()
  cph <- list(name = kwb.pkgbuild:::kwb_string(), start_year = 2018)
  kwb.pkgbuild:::use_mit_license(copyright_holder = cph)})
})

