#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_description() works", {

  aut <- list(name = "Michael Rustler",
              orcid = NULL,
              url = "https://mrustl.de")
  withr::with_dir(create_pkg_temp(), {
    kwb.pkgbuild:::use_description(author = aut,
                                 funder = "BMBF")})
})

