#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2018-12-20 11:03:50.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("create_empty_branch_ghpages() works", {

  expect_error(
    kwb.pkgbuild:::create_empty_branch_ghpages()
    # Specify the name of the repo to be checked out with parameter 'repo'
  )

})

