#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2018-12-17 16:23:09.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("set_github_user() works", {
  skip_on_travis()
  kwb.pkgbuild:::set_github_user(git_username = "mrustl",
                                 git_fullname = "Michael Rustler")

})

