#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_gitlab_ci_ghpages() works", {
  old_wd <- create_pkg_temp()
  kwb.pkgbuild:::use_gitlab_ci_ghpages()
  setwd(old_wd)
})

