#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("use_pkg() works", {
  withr::with_dir(create_pkg_temp(),{
  usethis::proj_set(getwd())
  kwb.pkgbuild:::use_pkg()})
})

