#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2018-12-17 16:23:09.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("write_ignorepattern_to_file() works", {

    kwb.pkgbuild:::write_ignorepattern_to_file("docs",
                                               comment = "#ignore docs",
                                               ".gitignore")

  kwb.pkgbuild:::write_ignorepattern_to_file("docs",,
                                             ".gitignore")

})

