#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2018-12-20 11:03:49.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_pkg_dir_nested() works", {

  expect_error(
    kwb.pkgbuild:::check_pkg_dir_nested()
    # argument "pkg_dir" is missing, with no default
  )

})

