#' @keywords internal
#' @noRd
read_gitlab_ci_template <- function(name) {
  yml <- system.file(sprintf("templates/%s", name),
                          package = "kwb.pkgbuild")

  readLines(yml)
}

#' @keywords internal
#' @noRd
#' @importFrom sessioninfo package_info
write_gitlab_ci <- function(yml_vector, dest_dir = getwd(), ignore) {

  calling_function_name <- deparse(sys.calls()[[1]])

  meta_creation <- sessioninfo::package_info("kwb.pkgbuild")

  meta_creation <- meta_creation[meta_creation$package == "kwb.pkgbuild",]


  message <- sprintf(
"##############################################################################
### Autogenerated with R package %s v%s
### (installed from '%s' source code on %s)
### by calling the function %s
### (file created at: %s)
##############################################################################\n\n",
meta_creation$package,
meta_creation$ondiskversion,
meta_creation$source,
meta_creation$date,
calling_function_name,
Sys.time())


  yml_vector <- c(message, yml_vector)

  writeLines(text = yml_vector,
             con =  file.path(dest_dir, ".gitlab-ci.yml"))

  if (ignore) write_to_rbuildignore(ignore_pattern = "^.gitlab-ci\\.yml$")
}

#' @keywords internal
# ' @noRd
gitlab_ci_template_docs <- function() {

  read_gitlab_ci_template("gitlab_ci_template_docs.yml")

}

#' @keywords internal
#' @noRd
gitlab_ci_template_ghpages <- function() {

  read_gitlab_ci_template("gitlab_ci_template_ghpages.yml")

}

#' @keywords internal
#' @noRd
gitlab_ci_template_pkgdown <- function() {

  read_gitlab_ci_template("gitlab_ci_template_pkgdown.yml")

}


#' @keywords internal
#' @noRd
gitlab_ci_template_blogdown <- function() {

  read_gitlab_ci_template("gitlab_ci_template_blogdown.yml")

}

# use_gitlab_ci_docs -----------------------------------------------------------
#' Adds .gitlab-ci.yml (if repo contains a "docs" subfolder)
#' @param dest_dir directoy to write (default:
#' getwd())
#' @param yml_vector a yml imported as string vector (default: gitlab_ci_template_docs())
#' @return writes .gitlab-ci.yml and adds it .Rbuildignore
#' @importFrom fs file_exists
#' @export

use_gitlab_ci_docs <- function(dest_dir = getwd(),
                               yml_vector = gitlab_ci_template_docs()) {


if(dir.exists("docs")) {
  write_gitlab_ci(yml_vector, dest_dir = dest_dir, ignore = TRUE)
} else {
 warning("No 'docs' folder, no .gitlab-ci.yml created!")
}
}

# use_gitlab_ci_ghpages---------------------------------------------------------
#' Adds .gitlab-ci.yml (which should be saved in root dir of "gh-pages" branch)
#' @param dest_dir directoy to write (default:
#' getwd())
#' @param yml_vector a yml imported as string vector (default: gitlab_ci_template_ghpages())
#' @return writes .gitlab-ci.yml
#' @importFrom fs file_exists
#' @export

use_gitlab_ci_ghpages <- function(dest_dir = getwd(),
                                  yml_vector = gitlab_ci_template_ghpages()) {


  write_gitlab_ci(yml_vector, dest_dir = dest_dir, ignore = FALSE)

}

# use_gitlab_ci_blogdown--------------------------------------------------------
#' Adds .gitlab-ci.yml (if repo contains on root in a "gh-pages" branch)
#' @param dest_dir directoy to write (default:
#' getwd())
#' @param yml_vector a yml imported as string vector (default: gitlab_ci_template_blogdown())
#' @return writes .gitlab-ci.yml
#' @importFrom fs file_exists
#' @export

use_gitlab_ci_blogdown <- function(dest_dir = getwd(),
                                  yml_vector = gitlab_ci_template_blogdown()) {


  write_gitlab_ci(yml_vector, dest_dir = dest_dir, ignore = TRUE)

}

# use_gitlab_ci_pkgdown--------------------------------------------------------
#' Adds .gitlab-ci.yml
#' @param dest_dir directoy to write (default:
#' getwd())
#' @param yml_vector a yml imported as string vector (default: gitlab_ci_template_pkgdown(),
#' where "<owner>/<repo>" is replaced with value from DESCRIPTION specified in
#' field URL, e.g. https://github.com/KWB-R/kwb.pkgbuild" sets
#' "KWB-R/kwb.pkgbuild" as "<owner>/<repo>")
#' @return writes .gitlab-ci.yml
#' @importFrom stringr str_remove
#' @importFrom desc desc_get
#' @export

use_gitlab_ci_pkgdown <- function(dest_dir = getwd(),
                                  yml_vector = gitlab_ci_template_pkgdown()) {


  owner_repo <- stringr::str_remove(desc::desc_get("URL"),
                                   "^http(s)?://github.com/")

  yml_vector <- stringr::str_replace(yml_vector,
                       pattern = "<owner>/<repo>",
                       replacement = owner_repo)



  write_gitlab_ci(yml_vector, dest_dir = dest_dir, ignore = TRUE)


}
